### PR TITLE
Add support for mhchem

### PR DESCRIPTION
**Pull request by physikerwelt**
Enable support for chemistry in MathJax-node

Bug: https://phabricator.wikimedia.org/T125295

### CODE REVIEW

**Comment by physikerwelt** [comment]
ping @wikimedia/math

**Comment by physikerwelt** [comment]
merge #14 first

**Comment by d00rman** [comment]
@physikerwelt please release the new version of the package on npmjs and tag this repo afterwards.

**Comment by physikerwelt** [comment]
@d00rman done.

**Comment by d00rman** [comment]
thnx!

**Pull request merged**
